digidotcom/xbee-java

library/src/test/java/com/digi/xbee/api/models/XBeeProtocolTest.java
The `XbeeProtocolTest.testDetermineProtocol()` test fails with a `FileNotFoundException` if the path to the directory housing the project contains a space. I encountered this attempting to compile on Windows with the repository cloned to a path like "C:\Users\FirstName LastName\digidotcom\XBeeJavaLibrary". The space in the user directory is converted to "%20" in the URL, which does not get translated back correctly to a space.
This patch corrects the issue by obtaining an InputStream directly to the file.
=> XbeeProtocolTest.testDetermineProtocol Fails When Space in Path

library/src/main/java/com/digi/xbee/api/NodeDiscovery.java, library/src/main/java/com/digi/xbee/api/models/HardwareVersionEnum.java, library/src/main/java/com/digi/xbee/api/models/XBeeProtocol.java
- Added new devices to the protocol and hardware tables.
- Modified node discovery feature for the S1B modules.
=> Implemented support for the new S1B modules.

examples/communication/ip/ConnectToEchoServerSample/ReadMe.txt, examples/communication/ip/ConnectToEchoServerSample/pom.xml, examples/communication/ip/ConnectToEchoServerSample/src/com/digi/xbee/api/connecttoechoserver/MainApp.java
- Although the example uses the CellularDevice class, it is also valid
for the WiFiDevice one.
- The example is located in the 'communication/ip' category. More examples
will be added here in the future.
https://jira.digi.com/browse/XBJAPI-294
=> cellular: add the connect to echo server example

library/src/main/java/com/digi/xbee/api/WiFiDevice.java, library/src/main/java/com/digi/xbee/api/models/AccessPoint.java, library/src/main/java/com/digi/xbee/api/models/WiFiEncryptionType.java, library/src/test/java/com/digi/xbee/api/AccessPointsDiscoverTest.java, library/src/test/java/com/digi/xbee/api/ConnectToAccessPointTest.java, library/src/test/java/com/digi/xbee/api/WiFiDeviceTest.java, library/src/test/java/com/digi/xbee/api/models/AccessPointTest.java, library/src/test/java/com/digi/xbee/api/models/WiFiEncryptionTypeTest.java
- Added a new enumerator (WiFiAssociationIndicationStatus) to list the
possible encryption types for the Wi-Fi access points.
- Added the AccessPoint class that represents an access point.
- Added new methods to discover access points, get a specific one, connect
and disconnect.
- Added new methods to get and set the Wi-Fi receive timeout, used to
connect, disconnect and discover access points.
- Written the unit tests for the new code and updated some others.
=> wifi: add support to discover and connect to access points

library/src/main/java/com/digi/xbee/api/CellularDevice.java, library/src/main/java/com/digi/xbee/api/IPDevice.java, library/src/main/java/com/digi/xbee/api/WiFiDevice.java, library/src/main/java/com/digi/xbee/api/models/IPAddressingMode.java, library/src/test/java/com/digi/xbee/api/CellularDeviceTest.java, library/src/test/java/com/digi/xbee/api/GetDestinationIPAddressTest.java, library/src/test/java/com/digi/xbee/api/IPDeviceTest.java, library/src/test/java/com/digi/xbee/api/SetDestinationIPAddressTest.java, library/src/test/java/com/digi/xbee/api/WiFiDeviceTest.java, library/src/test/java/com/digi/xbee/api/models/IPAddressingModeTest.java
https://jira.digi.com/browse/XBJAPI-348
=> wifi: add IP addressing functionality

examples/configuration/ConnectToAccessPointSample/ReadMe.txt, examples/configuration/ConnectToAccessPointSample/pom.xml, examples/configuration/ConnectToAccessPointSample/src/com/digi/xbee/api/connecttoaccesspoint/MainApp.java
The example is located in the 'configuration' category.
https://jira.digi.com/browse/XBJAPI-359
=> wifi: add the connect to access point example

examples/communication/ip/ReceiveIPDataSample/ReadMe.txt, examples/communication/ip/ReceiveIPDataSample/pom.xml, examples/communication/ip/ReceiveIPDataSample/src/com/digi/xbee/api/receiveipdata/MainApp.java, examples/communication/ip/ReceiveIPDataSample/src/com/digi/xbee/api/receiveipdata/MyIPDataReceiveListener.java, examples/communication/ip/SendIPDataSample/ReadMe.txt, examples/communication/ip/SendIPDataSample/pom.xml, examples/communication/ip/SendIPDataSample/src/com/digi/xbee/api/sendipdata/MainApp.java
The examples are located in the 'communication/ip' category.
https://jira.digi.com/browse/XBJAPI-371
=> ip: add the send IP data and receive IP data examples

library/src/main/java/com/digi/xbee/api/IPDevice.java, library/src/main/java/com/digi/xbee/api/WiFiDevice.java, library/src/test/java/com/digi/xbee/api/AccessPointsScanTest.java, library/src/test/java/com/digi/xbee/api/ConnectToAccessPointTest.java, library/src/test/java/com/digi/xbee/api/WiFiDeviceTest.java
- Renamed "discoverAccessPoints" method to "scanAccessPoints".
- Renamed the "Wi-Fi receive timeout" to "access point timeout" and updated
the method names.
- Updated references and tests.
https://jira.digi.com/browse/XBJAPI-357
https://jira.digi.com/browse/XBJAPI-358
=> wifi: rename discover access points and Wi-Fi receive timeout methods

examples/communication/ip/KnockKnockSample/ReadMe.txt, examples/communication/ip/KnockKnockSample/pom.xml, examples/communication/ip/KnockKnockSample/src/com/digi/xbee/api/knockknock/KnockKnockProtocol.java, examples/communication/ip/KnockKnockSample/src/com/digi/xbee/api/knockknock/MainApp.java, examples/communication/ip/KnockKnockSample/src/com/digi/xbee/api/knockknock/WebServer.java
The example is located in the "communication/ip" category.
https://jira.digi.com/browse/XBJAPI-360
=> ip: add the Knock Knock example (web server connection)

library/src/main/java/com/digi/xbee/api/WiFiDevice.java, library/src/test/java/com/digi/xbee/api/WiFiDeviceTest.java
- Added the corresponding unit tests.
=> wifi: add a method to get the access point the module is connected to

library/src/main/java/com/digi/xbee/api/connection/DataReader.java
https://github.com/digidotcom/XBeeJavaLibrary/issues/53
=> fix #53: check that 64-bit address is not unknown before obtaining the remote XBee device from the network

library/src/main/java/com/digi/xbee/api/AbstractXBeeDevice.java, library/src/main/java/com/digi/xbee/api/NodeDiscovery.java
It also fixes the node discovery of remote SX devices.
=> fix #101: avoid reading the 16-bit address when the protocol is SX

library/src/main/java/com/digi/xbee/api/models/HardwareVersionEnum.java, library/src/main/java/com/digi/xbee/api/models/XBeeProtocol.java, library/src/test/java/com/digi/xbee/api/models/HardwareVersionEnumTest.java
- Added support for 3G, LTE Verizon, LTE ATT and NB-IoT.
Signed-off-by: Héctor González <hector.gonzalez@digi.com>
=> cellular: add support for new hardware versions

library/src/main/java/com/digi/xbee/api/connection/android/AndroidXBeeInterface.java
Fix for  #125 - Ability to support FT-X based Adapters like SparkFun's XBee Explorer. 
I listed out other FTDI chips, but as I am not sure if they are completely compatible, I left them commented out.
=> Change a single hardcoded FTDI USB Product ID to a list.

library/src/main/java/com/digi/xbee/api/packet/raw/RX16IOPacket.java, library/src/main/java/com/digi/xbee/api/packet/raw/RX16Packet.java, library/src/main/java/com/digi/xbee/api/packet/raw/RX64IOPacket.java, library/src/main/java/com/digi/xbee/api/packet/raw/RX64Packet.java, library/src/test/java/com/digi/xbee/api/packet/raw/RX16IOPacketTest.java, library/src/test/java/com/digi/xbee/api/packet/raw/RX16PacketTest.java, library/src/test/java/com/digi/xbee/api/packet/raw/RX64IOPacketTest.java, library/src/test/java/com/digi/xbee/api/packet/raw/RX64PacketTest.java
This was causing the library to throw an exception when the local module
received data packets from remotes that were too far.
=> packets: increase the upper limit of the packet RSSI value from 100 to 255

library/src/test/java/com/digi/xbee/api/connection/DataReaderGetRemoteXBeeDeviceFromPacketTest.java
Added test case for unknown 64-bit address in ReceivePacket.
DataReader should no more crash from exceptions.
=> test: add unknown 64-bit address test for DataReader

library/src/main/java/com/digi/xbee/api/AbstractXBeeDevice.java, library/src/main/java/com/digi/xbee/api/DataReader.java, library/src/main/java/com/digi/xbee/api/models/OperatingMode.java
- Completed the list of operating modes.
- If the device cannot be discovered in API mode, the library checks if it is
in AT mode by entering command mode. In some scenarios like a hardware reset
or recovery mode, the module could be in API mode, but the library cannot
find it and determines that it is in AT mode (raising an exception). To avoid
that, the library now asks for the actual operating mode after entering
command mode.
- Added a new method to exit command mode.
=> devices: read the actual operating mode when the device is in AT mode

library/src/main/java/com/digi/xbee/api/models/XBeePacketsQueue.java, library/src/test/java/com/digi/xbee/api/models/XBeePacketsQueueTest.java
This problem was causing the 'readDataFrom' method to return the first
data packet on the queue, not the first one from the given remote device.
=> packets_queue: fix an issue when the device's 16-bit address is unknown

library/src/main/java/com/digi/xbee/api/AbstractXBeeDevice.java, library/src/main/java/com/digi/xbee/api/XBeeDevice.java
- readPacket()
- readPacket(timeout)
- readPacketFrom(remoteDevice)
- readPacketFrom(remoteDevice, timeout)
Once a packet has been read with one of these methods, it is removed from
the queue and cannot be read again.
=> devices: add several methods to read received packets synchronously

library/src/main/java/com/digi/xbee/api/models/HardwareVersionEnum.java, library/src/main/java/com/digi/xbee/api/models/XBeeProtocol.java
- 0x56: XBee 3 Cellular LTE-M/NB-IoT Low Power
- 0x57: XBee RR TH Pro/Non-Pro
https://onedigi.atlassian.net/browse/XBJAPI-537
https://onedigi.atlassian.net/browse/XBJAPI-538
=> hardware: add new versions to the supported hardware list
