library/src/main/java/com/digi/xbee/api/models/XBeeProtocol.java

Signed-off-by: David Escalona <david.escalona@digi.com>

s1b_dm: add DigiMesh support for S1B (S2C) sevices

---

library/src/main/java/com/digi/xbee/api/models/NetworkProtocol.java
library/src/main/java/com/digi/xbee/api/packet/APIFrameType.java
library/src/main/java/com/digi/xbee/api/packet/cellular/RXSMSPacket.java
library/src/main/java/com/digi/xbee/api/packet/cellular/TXSMSPacket.java
library/src/main/java/com/digi/xbee/api/packet/network/RXIPv4Packet.java
library/src/main/java/com/digi/xbee/api/packet/network/TXIPv4Packet.java
library/src/test/java/com/digi/xbee/api/models/NetworkProtocolTest.java
library/src/test/java/com/digi/xbee/api/packet/cellular/RXSMSPacketTest.java
library/src/test/java/com/digi/xbee/api/packet/cellular/TXSMSPacketTest.java
library/src/test/java/com/digi/xbee/api/packet/network/RXIPv4PacketTest.java
library/src/test/java/com/digi/xbee/api/packet/network/TXIPv4PacketTest.java

* New TX SMS, RX SMS, TX IPv4 and RX IPv4 frames with their corresponding
unit tests.
* New Network Protocol enumeration.
https://jira.digi.com/browse/XBJAPI-292

cellular: add support for XBee Cellular API frames

---

library/src/main/java/com/digi/xbee/api/models/XBeeTransmitStatus.java
library/src/test/java/com/digi/xbee/api/models/XBeeTransmitStatusTest.java

https://jira.digi.com/browse/XBJAPI-292

cellular: add new Transmit Status codes.

---

library/src/main/java/com/digi/xbee/api/models/ModemStatusEvent.java

cellular: add new Modem Status events

---

examples/communication/cellular/ReceiveSMSSample/ReadMe.txt
examples/communication/cellular/ReceiveSMSSample/pom.xml
examples/communication/cellular/ReceiveSMSSample/src/com/digi/xbee/api/receivesms/MainApp.java
examples/communication/cellular/ReceiveSMSSample/src/com/digi/xbee/api/receivesms/MySMSReceiveListener.java
examples/communication/cellular/SendSMSSample/ReadMe.txt
examples/communication/cellular/SendSMSSample/pom.xml
examples/communication/cellular/SendSMSSample/src/com/digi/xbee/api/sendsms/MainApp.java

- Both examples are located in the 'communication/cellular' category.
https://jira.digi.com/browse/XBJAPI-294

cellular: add receive and send SMS examples

---

pom.xml

pom: update Java version to 1.7 and Maven compiler version to 3.6.0

---

library/src/main/java/com/digi/xbee/api/CellularDevice.java
library/src/main/java/com/digi/xbee/api/models/CellularAssociationIndicationStatus.java
library/src/test/java/com/digi/xbee/api/CellularDeviceTest.java

The cellular association indication statuses have also been updated
according to the latest firmware documentation.

cellular: add method to know if the device is connected to the Internet

---

examples/android/XBeeManagerSample/ReadMe.txt

android: add reference to XBee Manager sample

---

README.md

readme: add references to Wi-Fi and Cellular protocols support

---

distribution/pom.xml
examples/communication/ReceiveDataPollingSample/pom.xml
examples/communication/ReceiveDataSample/pom.xml
examples/communication/ReceiveModemStatusSample/pom.xml
examples/communication/SendBroadcastDataSample/pom.xml
examples/communication/SendDataAsyncSample/pom.xml
examples/communication/SendDataSample/pom.xml
examples/communication/cellular/ReceiveSMSSample/pom.xml
examples/communication/cellular/SendSMSSample/pom.xml
examples/communication/explicit/ReceiveExplicitDataPollingSample/pom.xml
examples/communication/explicit/ReceiveExplicitDataSample/pom.xml
examples/communication/explicit/SendBroadcastExplicitDataSample/pom.xml
examples/communication/explicit/SendExplicitDataAsyncSample/pom.xml
examples/communication/explicit/SendExplicitDataSample/pom.xml
examples/communication/ip/ConnectToEchoServerSample/pom.xml
examples/communication/ip/KnockKnockSample/pom.xml
examples/communication/ip/ReceiveIPDataSample/pom.xml
examples/communication/ip/SendIPDataSample/pom.xml
examples/configuration/ConnectToAccessPointSample/pom.xml
examples/configuration/ManageCommonParametersSample/pom.xml
examples/configuration/ResetModuleSample/pom.xml
examples/configuration/SetAndGetParametersSample/pom.xml
examples/io/IOSamplingSample/pom.xml
examples/io/LocalADCSample/pom.xml
examples/io/LocalDIOSample/pom.xml
examples/io/RemoteADCSample/pom.xml
examples/io/RemoteDIOSample/pom.xml
examples/network/DiscoverDevicesSample/pom.xml
library/pom.xml
pom.xml

version: update library to version 1.2.0

---

examples/communication/ReceiveDataPollingSample/ReadMe.txt
examples/communication/ReceiveDataSample/ReadMe.txt
examples/communication/ReceiveModemStatusSample/ReadMe.txt
examples/communication/SendBroadcastDataSample/ReadMe.txt
examples/communication/SendDataAsyncSample/ReadMe.txt
examples/communication/SendDataSample/ReadMe.txt
examples/communication/cellular/ReceiveSMSSample/ReadMe.txt
examples/communication/cellular/SendSMSSample/ReadMe.txt
examples/communication/explicit/ReceiveExplicitDataPollingSample/ReadMe.txt
examples/communication/explicit/ReceiveExplicitDataSample/ReadMe.txt
examples/communication/explicit/SendBroadcastExplicitDataSample/ReadMe.txt
examples/communication/explicit/SendExplicitDataAsyncSample/ReadMe.txt
examples/communication/explicit/SendExplicitDataSample/ReadMe.txt
examples/communication/ip/ConnectToEchoServerSample/ReadMe.txt
examples/communication/ip/KnockKnockSample/ReadMe.txt
examples/communication/ip/ReceiveIPDataSample/ReadMe.txt
examples/communication/ip/SendIPDataSample/ReadMe.txt
examples/configuration/ConnectToAccessPointSample/ReadMe.txt
examples/configuration/ManageCommonParametersSample/ReadMe.txt
examples/configuration/ResetModuleSample/ReadMe.txt
examples/configuration/SetAndGetParametersSample/ReadMe.txt
examples/io/IOSamplingSample/ReadMe.txt
examples/io/LocalADCSample/ReadMe.txt
examples/io/LocalDIOSample/ReadMe.txt
examples/io/RemoteADCSample/ReadMe.txt
examples/io/RemoteDIOSample/ReadMe.txt
examples/network/DiscoverDevicesSample/ReadMe.txt

examples: add compatible protocols to ReadMe files

---

release_notes.txt

release_notes: update release notes for version 1.2.0

---

library/src/main/java/com/digi/xbee/api/models/HardwareVersionEnum.java
library/src/main/java/com/digi/xbee/api/models/XBeeProtocol.java

cellular: add support for new Cellular variants

---

library/src/main/java/com/digi/xbee/api/models/HardwareVersionEnum.java
library/src/main/java/com/digi/xbee/api/models/XBeeProtocol.java

- 0x41 - MINI-HAWK
- 0x42 - HAWK SMT
- 0x43 - HAWK TH
- 0x45 - XB8X

hardware: add support for new hardware variants

---

.gitignore
README.md
library/src/main/java/com/digi/xbee/api/AbstractXBeeDevice.java
library/src/main/java/com/digi/xbee/api/XBeeDevice.java
library/src/main/java/com/digi/xbee/api/connection/DataReader.java
library/src/main/java/com/digi/xbee/api/listeners/IUserDataRelayReceiveListener.java
library/src/main/java/com/digi/xbee/api/models/RelayInterface.java
library/src/main/java/com/digi/xbee/api/models/UserDataRelayMessage.java
library/src/main/java/com/digi/xbee/api/packet/APIFrameType.java
library/src/main/java/com/digi/xbee/api/packet/XBeePacketParser.java
library/src/main/java/com/digi/xbee/api/packet/relay/UserDataRelayOutputPacket.java
library/src/main/java/com/digi/xbee/api/packet/relay/UserDataRelayPacket.java

* Added classes for the User Data Relay and User Data Relay Output packets.
* Created methods to send a User Data Relay message and register a listener
to get incoming messages.

relay: add support for User Data Relay frames

---

examples/communication/relay/ReceiveUserDataRelaySample/ReadMe.txt
examples/communication/relay/ReceiveUserDataRelaySample/pom.xml
examples/communication/relay/ReceiveUserDataRelaySample/src/com/digi/xbee/api/receiveuserdatarelay/MainApp.java
examples/communication/relay/ReceiveUserDataRelaySample/src/com/digi/xbee/api/receiveuserdatarelay/MyUserDataRelayReceiveListener.java
examples/communication/relay/SendUserDataRelaySample/ReadMe.txt
examples/communication/relay/SendUserDataRelaySample/pom.xml
examples/communication/relay/SendUserDataRelaySample/src/com/digi/xbee/api/senduserdatarelay/MainApp.java
library/src/main/java/com/digi/xbee/api/XBeeDevice.java
pom.xml

- communication/relay/SendUserDataRelaySample
- communication/relay/ReceiveUserDataRelaySample

examples: add new samples to send and receive User Data Relay messages

---

library/src/main/java/com/digi/xbee/api/AbstractXBeeDevice.java
library/src/main/java/com/digi/xbee/api/BluetoothAuthentication.java
library/src/main/java/com/digi/xbee/api/XBeeDevice.java
library/src/main/java/com/digi/xbee/api/utils/srp/SrpConstants.java
library/src/main/java/com/digi/xbee/api/utils/srp/SrpUtils.java

Added also a couple of methods in the SRPUtils class to generate a salt
and verifier.

ble: add new method to update the Bluetooth password

---

examples/communication/bluetooth/ReceiveBluetoothFileSample/ReadMe.txt
examples/communication/bluetooth/ReceiveBluetoothFileSample/pom.xml
examples/communication/bluetooth/ReceiveBluetoothFileSample/src/com/digi/xbee/api/receivebluetoothfile/MainApp.java
examples/communication/bluetooth/ReceiveBluetoothFileSample/src/com/digi/xbee/api/receivebluetoothfile/MyBluetoothDataReceiveListener.java
pom.xml

This example is used in conjunction with the 'XBee BLE Microcontroller'
example of the Mobile SDK.

examples: add new example to receive a file from the Bluetooth interface

---

release_notes.txt

release_notes: update release notes for version 1.3.0

---

library/src/test/java/com/digi/xbee/api/XBeeDeviceDetermineOperatingModeTest.java

devices: fix the "Determine operating mode" test

---

library/src/main/java/com/digi/xbee/api/models/HardwareVersionEnum.java
library/src/main/java/com/digi/xbee/api/models/XBeeProtocol.java

- 0x58: XBee 3 Cellular Global Cat 4
- 0x59: XBee 3 Cellular North America Cat 4
- 0x5A: XBee XR 900 TH
- 0x5B: XBee XR 868 TH
https://onedigi.atlassian.net/browse/XBJAPI-540

hardware: add new versions to the supported hardware list
